### ISSUE TITLE
C语言的式子运算顺序

### ISSUE THREAD

**Issue by Xuyonglong** [zccz14/QA#2]
在C语言的表达式中出现||和&&时的运算顺序是什么？有什么特殊规则？与编译器有关吗？
如‘0’||（b+2）&&（a--）||（c=1）

**Comment by zccz14** [comment]
根据 [C 语言运算符优先级表](http://baike.baidu.com/item/%E8%BF%90%E7%AE%97%E7%AC%A6%E4%BC%98%E5%85%88%E7%BA%A7#2)

`&&` 的优先级比 `||` 要高，两个都是右结合性。

先算 `&&`。

`'0' || (b + 2) && (a--) || c = 1` 这里的话就是

`('0' || ((b + 2) && (a--))) || c = 1`

这个样子。

**Comment by zccz14** [comment]
关于表达式的求值，参见 expression evaluate 问题。

关于这个有个著名的算法叫调度场算法(Shunting Yard Algorithm)。

可以自行搜索一下。

**Comment by zccz14** [comment]
表达式求值的规则由语言标准设定的运算符优先级、结合性直接确定。

跟编译器无关。

但是如果你的表达式不符合规范，可能会出现未定义行为（UB: Undefined Behavior）：

> 如在一个表达式中多次修改同一个变量。

这个要看编译器实现，但一般不允许程序员写出这样的代码。

**Comment by zccz14** [comment]
> C语言规定：
> Accessing a volatile object, modifying an object, modifying a file, or calling a function that does any of those operations are all side effects, which are changes in the state of the execution environment. Evaluation of an expression may produce side effects. At certain specified points in the execution sequence called sequence points, all side effects of previous evaluations shall be complete and no side effects of subsequent evaluations shall have taken place.
> 访问易变对象，修改对象或文件，或者调用包含这些操作的函数都是副作用，它们都会改变执行环境的状态。计算表达式也会引起副作用。执行序列中某些特定的点被称为序列点。在序列点上，该点之前所有运算的副作用都应该结束，并且后继运算的副作用还没发生。

**Comment by Xuyonglong** [comment]
>是个经典的数据结构（栈）问题
这是指栈堆吗？把数据一个个压进去然后一个个提出来的那个数据结构？
在c++里用push和pop，在C里则是要自己创建这个数据结构是吗？ @zccz14

**Comment by zccz14** [comment]
> 这是指栈堆吗？把数据一个个压进去然后一个个提出来的那个数据结构？在c++里用push和pop，在C里则是要自己创建这个数据结构是吗？ 

是的，Stack这种数据结构在 C++ 的 STL (标准模板库) 中有实现。

**Comment by Xuyonglong** [comment]
好的，O(∩_∩)O谢谢
