### ISSUE TITLE
如何看待5月2日发布的Dojo2

### ISSUE THREAD

**Issue by Thrimbda** [zccz14/QA#5]
看过一些有关Dojo的文章[[1]](https://medium.com/@mikeal/react-is-the-new-dojo-18bd9059378f)[[2]](http://www.infoq.com/cn/news/2018/05/js-foundation-announces-dojo-2)，没有详细的了解= =直觉上觉得它跟React有些像，那么
- 你怎么看这个框架？
- 这个古老框架的全新版本与React/Vue的竞争力？
- 还有什么补充的？

**Comment by zccz14** [comment]
类 React 的框架太多了，React 当然也不是设计最好的一个。但 React 的胜利在于生态，前端的开发从来不是一个人的事，也不是一个团队的事。
至于 Dojo，我具体也了解得不多。

**Comment by Thrimbda** [comment]
阮一峰：
> 前端框架 Dojo 发布了2.0版，它跟 jQuery 是一个年代的，至今不放弃也算值得尊敬了。我看了一下 API，核心概念也是虚拟 DOM，没看到任何令人眼前一亮的创意，我不觉得它有机会赢得大量用户。

FYI
